import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../../components/navbar";
import { AuthProvider } from "../../context/auth-context";
import { QueryClientProviderWrapper } from '../../components/tanstack'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
          <QueryClientProviderWrapper>
        <AuthProvider>
        <Navbar />
        <main className="pt-4">{children}</main>
      </AuthProvider>
      </QueryClientProviderWrapper>
      </body>
    </html>
  );
}
